### ISSUE TITLE
Unified atlas

### ISSUE THREAD

**Issue by cfhammill** [CoBrALab/atlases#5]
Would it be possible to include unified atlases for all label sets defined on the same anatomy? I know hippocampus-amygdala exists on scinet already for example.

**Comment by gdevenyi** [comment]
subcortical labels are defined on a different brain so that's not currently possible without an expert re-labelling of the 5 brains

for other label sets, the current label numbers have overlaps so we can't directly merge them without a renumbering. We have an unofficial one which we're not ready to release.

Going forward, my new MAGeT implementation can take in multiple label files per atlas, so merging won't be needed.

**Comment by cfhammill** [comment]
subcortical labels are defined on a different brain so that's not currently possible without an expert re-labelling of the 5 brains

> understood

for other label sets, the current label numbers have overlaps so we can't directly merge them without a renumbering. We have an unofficial one which we're not ready to release.

> seems relatively straight forward with `minc_label_ops -remap`

Going forward, my new MAGeT implementation can take in multiple label files per atlas, so merging won't be needed.

>  great! Thanks Gabe
